- type: replace
  path: /releases/name=capi/url
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/capi-1.79.0-ubuntu-xenial-315.10-20190423-231529-408537846.tgz
- type: replace
  path: /releases/name=capi/version
  value: 1.79.0
- type: replace
  path: /releases/name=capi/sha1
  value: 04e171ce24212e9a23d0a0958591327edcf895d9
- type: replace
  path: /releases/name=binary-buildpack/url
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/binary-buildpack-1.0.31-ubuntu-xenial-315.10-20190423-231236-392418301.tgz
- type: replace
  path: /releases/name=binary-buildpack/version
  value: 1.0.31
- type: replace
  path: /releases/name=binary-buildpack/sha1
  value: 441959b91cc6ff3eeb527e4517e5fb83ee7e29ee
- type: replace
  path: /releases/name=cf-networking/url
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/cf-networking-2.22.0-ubuntu-xenial-315.10-20190423-231354-660152439.tgz
- type: replace
  path: /releases/name=cf-networking/version
  value: 2.22.0
- type: replace
  path: /releases/name=cf-networking/sha1
  value: 77028eb32b3664ca80f8c223d1a4d53fc6233fd5
- type: replace
  path: /releases/name=uaa/url
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/uaa-72.0-ubuntu-xenial-315.10-20190423-231356-936934219.tgz
- type: replace
  path: /releases/name=uaa/version
  value: "72.0"
- type: replace
  path: /releases/name=uaa/sha1
  value: 61a469d65a98dba5534392834c6f29852e735185
- type: replace
  path: /releases/name=nats/url
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/nats-26-ubuntu-xenial-315.10-20190423-231008-813443992.tgz
- type: replace
  path: /releases/name=nats/version
  value: "26"
- type: replace
  path: /releases/name=nats/sha1
  value: 10d6bfa09cbd2bd7d72199220277742aa6c7dc7c
- type: replace
  path: /releases/name=diego/url
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/diego-2.30.0-ubuntu-xenial-315.10-20190423-231525-143610074.tgz
- type: replace
  path: /releases/name=diego/version
  value: 2.30.0
- type: replace
  path: /releases/name=diego/sha1
  value: e1fe93f30e5026149c8e6a12dfab819853ced87c
- type: replace
  path: /releases/name=routing/url
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/routing-0.187.0-ubuntu-xenial-315.10-20190423-231434-684229261.tgz
- type: replace
  path: /releases/name=routing/version
  value: 0.187.0
- type: replace
  path: /releases/name=routing/sha1
  value: b6282ff56f5571d5dee4be06bc73b966748d644b
- type: replace
  path: /releases/name=garden-runc/url
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/garden-runc-1.19.1-ubuntu-xenial-315.10-20190423-231506-094013462.tgz
- type: replace
  path: /releases/name=garden-runc/version
  value: 1.19.1
- type: replace
  path: /releases/name=garden-runc/sha1
  value: 21a7cc3ba264390bdb207afe468d65f67198064e
- type: replace
  path: /releases/name=loggregator/url
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/loggregator-105.3-ubuntu-xenial-315.10-20190423-231331-431676362.tgz
- type: replace
  path: /releases/name=loggregator/version
  value: "105.3"
- type: replace
  path: /releases/name=loggregator/sha1
  value: 4353b4532b3a358a82892aa9ad3ef1ecc4dd42d7
- type: replace
  path: /releases/name=go-buildpack/url
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/go-buildpack-1.8.35-ubuntu-xenial-315.10-20190423-231143-965256754.tgz
- type: replace
  path: /releases/name=go-buildpack/version
  value: 1.8.35
- type: replace
  path: /releases/name=go-buildpack/sha1
  value: 4e30561b5a589764001cacdb021f445fd5c7c77d
- type: replace
  path: /releases/name=php-buildpack/url
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/php-buildpack-4.3.72-ubuntu-xenial-315.10-20190423-231018-20413021.tgz
- type: replace
  path: /releases/name=php-buildpack/version
  value: 4.3.72
- type: replace
  path: /releases/name=php-buildpack/sha1
  value: 8f1672b6bbbec9f961dd674e5910bfd3195d009a
- type: replace
  path: /releases/name=cf-smoke-tests/url
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/cf-smoke-tests-40.0.51-ubuntu-xenial-315.10-20190423-231312-381043822.tgz
- type: replace
  path: /releases/name=cf-smoke-tests/version
  value: 40.0.51
- type: replace
  path: /releases/name=cf-smoke-tests/sha1
  value: e1d5e4474d31c5d0834b6c2e95d8398496886370
- type: replace
  path: /releases/name=java-buildpack/url
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/java-buildpack-4.18-ubuntu-xenial-315.10-20190423-231200-222038526.tgz
- type: replace
  path: /releases/name=java-buildpack/version
  value: "4.18"
- type: replace
  path: /releases/name=java-buildpack/sha1
  value: 4e9c79ddc0c120bd789cd387e1518c302d2a76d7
- type: replace
  path: /releases/name=ruby-buildpack/url
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/ruby-buildpack-1.7.36-ubuntu-xenial-315.10-20190423-231202-358704529.tgz
- type: replace
  path: /releases/name=ruby-buildpack/version
  value: 1.7.36
- type: replace
  path: /releases/name=ruby-buildpack/sha1
  value: af57592878d061d4b1c81e414d2b47302a5bc182
- type: replace
  path: /releases/name=statsd-injector/url
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/statsd-injector-1.10.0-ubuntu-xenial-315.10-20190423-231038-600504315.tgz
- type: replace
  path: /releases/name=statsd-injector/version
  value: 1.10.0
- type: replace
  path: /releases/name=statsd-injector/sha1
  value: 12133d19837c5cd14762c4a9a24fce246bd7e47e
- type: replace
  path: /releases/name=nodejs-buildpack/url
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/nodejs-buildpack-1.6.45-ubuntu-xenial-315.10-20190423-231141-951928179.tgz
- type: replace
  path: /releases/name=nodejs-buildpack/version
  value: 1.6.45
- type: replace
  path: /releases/name=nodejs-buildpack/sha1
  value: 94edc51b8ebf6e7f7b15d55fdb5f260dc255e5c3
- type: replace
  path: /releases/name=python-buildpack/url
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/python-buildpack-1.6.29-ubuntu-xenial-315.10-20190423-231158-934689641.tgz
- type: replace
  path: /releases/name=python-buildpack/version
  value: 1.6.29
- type: replace
  path: /releases/name=python-buildpack/sha1
  value: d0f5e051e24ad4bf797563a59aee6f1db501deb1
- type: replace
  path: /releases/name=staticfile-buildpack/url
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/staticfile-buildpack-1.4.40-ubuntu-xenial-315.10-20190423-231202-459375093.tgz
- type: replace
  path: /releases/name=staticfile-buildpack/version
  value: 1.4.40
- type: replace
  path: /releases/name=staticfile-buildpack/sha1
  value: b4052a3cef2b8edcca5d0e6bec1c791fd2d50e93
- type: replace
  path: /releases/name=dotnet-core-buildpack/url
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/dotnet-core-buildpack-2.2.7-ubuntu-xenial-315.10-20190423-231148-455199439.tgz
- type: replace
  path: /releases/name=dotnet-core-buildpack/version
  value: 2.2.7
- type: replace
  path: /releases/name=dotnet-core-buildpack/sha1
  value: a2dc2d62dd7a1a875fb1113380ce2888f13f648c
- type: replace
  path: /releases/name=cf-syslog-drain/url
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/cf-syslog-drain-10.1-ubuntu-xenial-315.10-20190423-231223-414169466.tgz
- type: replace
  path: /releases/name=cf-syslog-drain/version
  value: "10.1"
- type: replace
  path: /releases/name=cf-syslog-drain/sha1
  value: 73c7505d411f7339d4e1dd01b7f6493b6fac03a3
- type: replace
  path: /releases/name=bpm/url
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/bpm-1.0.4-ubuntu-xenial-315.10-20190423-231101-69175133.tgz
- type: replace
  path: /releases/name=bpm/version
  value: 1.0.4
- type: replace
  path: /releases/name=bpm/sha1
  value: c1f42a2bbf9344f9c58ff56b2ab91bf74f60510a
- type: replace
  path: /releases/name=loggregator-agent/url
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/loggregator-agent-3.9-ubuntu-xenial-315.10-20190423-231453-910969962.tgz
- type: replace
  path: /releases/name=loggregator-agent/version
  value: "3.9"
- type: replace
  path: /releases/name=loggregator-agent/sha1
  value: a4cb04140ee4b23c491126f9b8188f6be838ce79
- type: replace
  path: /releases/name=silk/url
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/silk-2.22.0-ubuntu-xenial-315.10-20190423-231419-072383269.tgz
- type: replace
  path: /releases/name=silk/version
  value: 2.22.0
- type: replace
  path: /releases/name=silk/sha1
  value: 9ff54bdfe6e9bda31eb569b466d0670e00b87163
- type: replace
  path: /releases/name=bpm/stemcell?
  value:
    os: ubuntu-xenial
    version: "315.10"
- type: replace
  path: /releases/name=capi/stemcell?
  value:
    os: ubuntu-xenial
    version: "315.10"
- type: replace
  path: /releases/name=binary-buildpack/stemcell?
  value:
    os: ubuntu-xenial
    version: "315.10"
- type: replace
  path: /releases/name=cf-networking/stemcell?
  value:
    os: ubuntu-xenial
    version: "315.10"
- type: replace
  path: /releases/name=cf-smoke-tests/stemcell?
  value:
    os: ubuntu-xenial
    version: "315.10"
- type: replace
  path: /releases/name=cf-syslog-drain/stemcell?
  value:
    os: ubuntu-xenial
    version: "315.10"
- type: replace
  path: /releases/name=diego/stemcell?
  value:
    os: ubuntu-xenial
    version: "315.10"
- type: replace
  path: /releases/name=dotnet-core-buildpack/stemcell?
  value:
    os: ubuntu-xenial
    version: "315.10"
- type: replace
  path: /releases/name=garden-runc/stemcell?
  value:
    os: ubuntu-xenial
    version: "315.10"
- type: replace
  path: /releases/name=go-buildpack/stemcell?
  value:
    os: ubuntu-xenial
    version: "315.10"
- type: replace
  path: /releases/name=java-buildpack/stemcell?
  value:
    os: ubuntu-xenial
    version: "315.10"
- type: replace
  path: /releases/name=loggregator/stemcell?
  value:
    os: ubuntu-xenial
    version: "315.10"
- type: replace
  path: /releases/name=loggregator-agent/stemcell?
  value:
    os: ubuntu-xenial
    version: "315.10"
- type: replace
  path: /releases/name=nats/stemcell?
  value:
    os: ubuntu-xenial
    version: "315.10"
- type: replace
  path: /releases/name=nodejs-buildpack/stemcell?
  value:
    os: ubuntu-xenial
    version: "315.10"
- type: replace
  path: /releases/name=php-buildpack/stemcell?
  value:
    os: ubuntu-xenial
    version: "315.10"
- type: replace
  path: /releases/name=python-buildpack/stemcell?
  value:
    os: ubuntu-xenial
    version: "315.10"
- type: replace
  path: /releases/name=routing/stemcell?
  value:
    os: ubuntu-xenial
    version: "315.10"
- type: replace
  path: /releases/name=ruby-buildpack/stemcell?
  value:
    os: ubuntu-xenial
    version: "315.10"
- type: replace
  path: /releases/name=silk/stemcell?
  value:
    os: ubuntu-xenial
    version: "315.10"
- type: replace
  path: /releases/name=staticfile-buildpack/stemcell?
  value:
    os: ubuntu-xenial
    version: "315.10"
- type: replace
  path: /releases/name=statsd-injector/stemcell?
  value:
    os: ubuntu-xenial
    version: "315.10"
- type: replace
  path: /releases/name=uaa/stemcell?
  value:
    os: ubuntu-xenial
    version: "315.10"
- type: replace
  path: /releases/name=bosh-dns-aliases/url
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/bosh-dns-aliases-0.0.3-ubuntu-xenial-315.10-20190423-231137-986273059.tgz
- type: replace
  path: /releases/name=bosh-dns-aliases/version
  value: 0.0.3
- type: replace
  path: /releases/name=bosh-dns-aliases/sha1
  value: 088d0833ba6257d3d0fbd9403c31d650261756ac
- type: replace
  path: /releases/name=log-cache/url
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/log-cache-2.2.0-ubuntu-xenial-315.10-20190423-231355-256926283.tgz
- type: replace
  path: /releases/name=log-cache/version
  value: 2.2.0
- type: replace
  path: /releases/name=log-cache/sha1
  value: 562b6ced0a5b8802c2a1cbe161691315450290d8
- type: replace
  path: /releases/name=credhub/url
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/credhub-2.3.0-ubuntu-xenial-315.10-20190423-231221-077770008.tgz
- type: replace
  path: /releases/name=credhub/sha1
  value: 885387f5a1ecdbc753610ebceeecb8e7c2d34e73
- type: replace
  path: /releases/name=credhub/version
  value: 2.3.0
- type: replace
  path: /releases/name=credhub/stemcell?
  value:
    os: ubuntu-xenial
    version: "315.10"
- type: replace
  path: /releases/name=cf-cli/url
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/cf-cli-1.13.0-ubuntu-xenial-315.10-20190423-231142-568754007.tgz
- type: replace
  path: /releases/name=cf-cli/sha1
  value: 7e569b8f08f6af648342ea2944147b7d4f458a58
- type: replace
  path: /releases/name=cf-cli/version
  value: 1.13.0
- type: replace
  path: /releases/name=cf-cli/stemcell?
  value:
    os: ubuntu-xenial
    version: "315.10"
- type: replace
  path: /releases/name=log-cache/stemcell?
  value:
    os: ubuntu-xenial
    version: "315.10"
- type: replace
  path: /releases/name=bosh-dns-aliases/stemcell?
  value:
    os: ubuntu-xenial
    version: "315.10"
- type: replace
  path: /releases/name=cflinuxfs3/url
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/cflinuxfs3-0.82.0-ubuntu-xenial-315.10-20190423-231307-135437592.tgz
- type: replace
  path: /releases/name=cflinuxfs3/sha1
  value: 868c051cc9bbcd97665d46dee9ace293ae4a6378
- type: replace
  path: /releases/name=cflinuxfs3/version
  value: 0.82.0
- type: replace
  path: /releases/name=cflinuxfs3/stemcell?
  value:
    os: ubuntu-xenial
    version: "315.10"
- type: replace
  path: /releases/name=pxc/url
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/pxc-0.16.0-ubuntu-xenial-315.10-20190423-231528-741029227.tgz
- type: replace
  path: /releases/name=pxc/sha1
  value: 1b59ae8a520f21ffef5de90badc0069130bd9276
- type: replace
  path: /releases/name=pxc/version
  value: 0.16.0
- type: replace
  path: /releases/name=pxc/stemcell?
  value:
    os: ubuntu-xenial
    version: "315.10"
- type: replace
  path: /releases/name=r-buildpack/url
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/r-buildpack-1.0.7-ubuntu-xenial-315.10-20190423-231200-40039915.tgz
- type: replace
  path: /releases/name=r-buildpack/sha1
  value: 262404872bb844a12549b5d94b357755ca7b1235
- type: replace
  path: /releases/name=r-buildpack/version
  value: 1.0.7
- type: replace
  path: /releases/name=r-buildpack/stemcell?
  value:
    os: ubuntu-xenial
    version: "315.10"
- type: replace
  path: /releases/name=nginx-buildpack/url
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/nginx-buildpack-1.0.9-ubuntu-xenial-315.10-20190423-231150-851004304.tgz
- type: replace
  path: /releases/name=nginx-buildpack/sha1
  value: 858e9dc1443b56020bd0d3df49909eecd86f7ddc
- type: replace
  path: /releases/name=nginx-buildpack/version
  value: 1.0.9
- type: replace
  path: /releases/name=nginx-buildpack/stemcell?
  value:
    os: ubuntu-xenial
    version: "315.10"
