- path: /releases/name=cf-mysql/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/cf-mysql-36.15.0-ubuntu-xenial-97-20180717-182122-837599814.tgz
- path: /releases/name=cf-mysql/version
  type: replace
  value: 36.15.0
- path: /releases/name=cf-mysql/sha1
  type: replace
  value: 33f28ccf4397732f1fa1aca143a941ffc5b919b9
- path: /releases/name=capi/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/capi-1.62.0-ubuntu-xenial-97-20180717-175607-293520809.tgz
- path: /releases/name=capi/version
  type: replace
  value: 1.62.0
- path: /releases/name=capi/sha1
  type: replace
  value: 08755d626b67e9b5a61593a2b388d71cee57b32e
- path: /releases/name=binary-buildpack/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/binary-buildpack-1.0.21-ubuntu-xenial-97-20180717-175003-128227201.tgz
- path: /releases/name=binary-buildpack/version
  type: replace
  value: 1.0.21
- path: /releases/name=binary-buildpack/sha1
  type: replace
  value: de3c57f8553af11c60046181c117ab6745a08632
- path: /releases/name=cf-networking/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/cf-networking-2.10.0-ubuntu-xenial-97-20180720-170823-135711548.tgz
- path: /releases/name=cf-networking/version
  type: replace
  value: 2.10.0
- path: /releases/name=cf-networking/sha1
  type: replace
  value: 99d2fe75dac943ed399f6eb5dbd6f50350c961eb
- path: /releases/name=uaa/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/uaa-60.2-ubuntu-xenial-97-20180717-175407-837713307.tgz
- path: /releases/name=uaa/version
  type: replace
  value: "60.2"
- path: /releases/name=uaa/sha1
  type: replace
  value: b61a1ac6c9325331acd5a2c29b33ab78426c0f6f
- path: /releases/name=nats/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/nats-25-ubuntu-xenial-97-20180720-191057-800979671.tgz
- path: /releases/name=nats/version
  type: replace
  value: "25"
- path: /releases/name=nats/sha1
  type: replace
  value: 93271df4700da4186bf3ebc1a07ee6db50b5618e
- path: /releases/name=diego/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/diego-2.13.0-ubuntu-xenial-97-20180717-231608-933469646.tgz
- path: /releases/name=diego/version
  type: replace
  value: 2.13.0
- path: /releases/name=diego/sha1
  type: replace
  value: b0d1edb654488de11c29480c847fbb4c3375bfe3
- path: /releases/name=routing/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/routing-0.179.0-ubuntu-xenial-97-20180717-175239-045249143.tgz
- path: /releases/name=routing/version
  type: replace
  value: 0.179.0
- path: /releases/name=routing/sha1
  type: replace
  value: fe4d4f0e269fd63aafbfc7f17ec34de08bb62af0
- path: /releases/name=consul/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/consul-195-ubuntu-xenial-97-20180717-175127-130205903.tgz
- path: /releases/name=consul/version
  type: replace
  value: "195"
- path: /releases/name=consul/sha1
  type: replace
  value: ef22dfd1d79dd92a70434df839a3e272ff950abf
- path: /releases/name=cflinuxfs2/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/cflinuxfs2-1.227.0-ubuntu-xenial-97-20180717-175011-487995406.tgz
- path: /releases/name=cflinuxfs2/version
  type: replace
  value: 1.227.0
- path: /releases/name=cflinuxfs2/sha1
  type: replace
  value: 30b860eeb6bd530e73e1286774d6a655d0e6b4d0
- path: /releases/name=garden-runc/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/garden-runc-1.15.1-ubuntu-xenial-97-20180717-175557-773049086.tgz
- path: /releases/name=garden-runc/version
  type: replace
  value: 1.15.1
- path: /releases/name=garden-runc/sha1
  type: replace
  value: 110f5c3b27a6c2b00b02dc73c7cf8ad8959b4440
- path: /releases/name=loggregator/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/loggregator-103.0-ubuntu-xenial-97-20180717-175209-78891645.tgz
- path: /releases/name=loggregator/version
  type: replace
  value: "103.0"
- path: /releases/name=loggregator/sha1
  type: replace
  value: 5e5d6568dd13edba4f91875b0abfec2267149896
- path: /releases/name=go-buildpack/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/go-buildpack-1.8.25-ubuntu-xenial-97-20180717-174924-215262.tgz
- path: /releases/name=go-buildpack/version
  type: replace
  value: 1.8.25
- path: /releases/name=go-buildpack/sha1
  type: replace
  value: eb31517fe000faae65925fc1e675979a5b225931
- path: /releases/name=php-buildpack/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/php-buildpack-4.3.57-ubuntu-xenial-97-20180717-175003-834755189.tgz
- path: /releases/name=php-buildpack/version
  type: replace
  value: 4.3.57
- path: /releases/name=php-buildpack/sha1
  type: replace
  value: 58aee9050d00b766a514f87172f95a09cf16118e
- path: /releases/name=cf-smoke-tests/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/cf-smoke-tests-40.0.5-ubuntu-xenial-97-20180717-175050-178113418.tgz
- path: /releases/name=cf-smoke-tests/version
  type: replace
  value: 40.0.5
- path: /releases/name=cf-smoke-tests/sha1
  type: replace
  value: 6a5f2f8047b01e3d22b99ead872c612dce7e75d1
- path: /releases/name=java-buildpack/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/java-buildpack-4.13.1-ubuntu-xenial-97-20180724-182150-733733596.tgz
- path: /releases/name=java-buildpack/version
  type: replace
  value: 4.13.1
- path: /releases/name=java-buildpack/sha1
  type: replace
  value: dcc1b091f6c27fe4fceed90349af3df5bc02df9c
- path: /releases/name=ruby-buildpack/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/ruby-buildpack-1.7.21-ubuntu-xenial-97-20180717-174938-293874823.tgz
- path: /releases/name=ruby-buildpack/version
  type: replace
  value: 1.7.21
- path: /releases/name=ruby-buildpack/sha1
  type: replace
  value: 741ac00a68cfc1c88ab78cdce908c53495da54d4
- path: /releases/name=statsd-injector/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/statsd-injector-1.3.0-ubuntu-xenial-97-20180717-175120-952949612.tgz
- path: /releases/name=statsd-injector/version
  type: replace
  value: 1.3.0
- path: /releases/name=statsd-injector/sha1
  type: replace
  value: 3975c5c3dea73c2854ae8583f177cb27dd945473
- path: /releases/name=nodejs-buildpack/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/nodejs-buildpack-1.6.28-ubuntu-xenial-97-20180717-175003-831605309.tgz
- path: /releases/name=nodejs-buildpack/version
  type: replace
  value: 1.6.28
- path: /releases/name=nodejs-buildpack/sha1
  type: replace
  value: d62cd4046efccaf5eff6a2152d6f96cca63e5609
- path: /releases/name=python-buildpack/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/python-buildpack-1.6.18-ubuntu-xenial-97-20180717-175003-183914959.tgz
- path: /releases/name=python-buildpack/version
  type: replace
  value: 1.6.18
- path: /releases/name=python-buildpack/sha1
  type: replace
  value: 1ed4d0687658d654ed3ee27a659d9c7ae8ddf303
- path: /releases/name=staticfile-buildpack/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/staticfile-buildpack-1.4.29-ubuntu-xenial-97-20180717-175003-128725909.tgz
- path: /releases/name=staticfile-buildpack/version
  type: replace
  value: 1.4.29
- path: /releases/name=staticfile-buildpack/sha1
  type: replace
  value: 4a0d5d7e9350cb3e905ff77d37dcb37e180f881d
- path: /releases/name=dotnet-core-buildpack/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/dotnet-core-buildpack-2.1.3-ubuntu-xenial-97-20180717-174938-293915832.tgz
- path: /releases/name=dotnet-core-buildpack/version
  type: replace
  value: 2.1.3
- path: /releases/name=dotnet-core-buildpack/sha1
  type: replace
  value: e7ee1442a00457b1fd490d5a9807d5569137a17f
- path: /releases/name=cf-syslog-drain/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/cf-syslog-drain-7.0-ubuntu-xenial-97-20180717-175135-408405181.tgz
- path: /releases/name=cf-syslog-drain/version
  type: replace
  value: "7.0"
- path: /releases/name=cf-syslog-drain/sha1
  type: replace
  value: c61ecaaba1fd3bf1441d12b8fd64b9ed9cd1579d
- path: /releases/name=bpm/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/bpm-0.9.0-ubuntu-xenial-97-20180717-184108-821578513.tgz
- path: /releases/name=bpm/version
  type: replace
  value: 0.9.0
- path: /releases/name=bpm/sha1
  type: replace
  value: d7dd23b890e4d713c87bc7ce15d6c0ba5539c90d
- path: /releases/name=loggregator-agent/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/loggregator-agent-2.0-ubuntu-xenial-97-20180717-175056-99856785.tgz
- path: /releases/name=loggregator-agent/version
  type: replace
  value: "2.0"
- path: /releases/name=loggregator-agent/sha1
  type: replace
  value: 602287674fec5e7fc881b4b0b9cf64d120219775
- path: /releases/name=silk/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/silk-2.10.0-ubuntu-xenial-97-20180720-171825-618395602.tgz
- path: /releases/name=silk/version
  type: replace
  value: 2.10.0
- path: /releases/name=silk/sha1
  type: replace
  value: 4a86c374000f863dfad82a34f7d03f16a24be1a1
- path: /releases/name=bpm/stemcell?
  type: replace
  value:
    os: ubuntu-xenial
    version: "97"
- path: /releases/name=capi/stemcell?
  type: replace
  value:
    os: ubuntu-xenial
    version: "97"
- path: /releases/name=cf-mysql/stemcell?
  type: replace
  value:
    os: ubuntu-xenial
    version: "97"
- path: /releases/name=binary-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-xenial
    version: "97"
- path: /releases/name=cf-networking/stemcell?
  type: replace
  value:
    os: ubuntu-xenial
    version: "97"
- path: /releases/name=cf-smoke-tests/stemcell?
  type: replace
  value:
    os: ubuntu-xenial
    version: "97"
- path: /releases/name=cf-syslog-drain/stemcell?
  type: replace
  value:
    os: ubuntu-xenial
    version: "97"
- path: /releases/name=cflinuxfs2/stemcell?
  type: replace
  value:
    os: ubuntu-xenial
    version: "97"
- path: /releases/name=consul/stemcell?
  type: replace
  value:
    os: ubuntu-xenial
    version: "97"
- path: /releases/name=diego/stemcell?
  type: replace
  value:
    os: ubuntu-xenial
    version: "97"
- path: /releases/name=dotnet-core-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-xenial
    version: "97"
- path: /releases/name=garden-runc/stemcell?
  type: replace
  value:
    os: ubuntu-xenial
    version: "97"
- path: /releases/name=go-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-xenial
    version: "97"
- path: /releases/name=java-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-xenial
    version: "97"
- path: /releases/name=loggregator/stemcell?
  type: replace
  value:
    os: ubuntu-xenial
    version: "97"
- path: /releases/name=loggregator-agent/stemcell?
  type: replace
  value:
    os: ubuntu-xenial
    version: "97"
- path: /releases/name=nats/stemcell?
  type: replace
  value:
    os: ubuntu-xenial
    version: "97"
- path: /releases/name=nodejs-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-xenial
    version: "97"
- path: /releases/name=php-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-xenial
    version: "97"
- path: /releases/name=python-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-xenial
    version: "97"
- path: /releases/name=routing/stemcell?
  type: replace
  value:
    os: ubuntu-xenial
    version: "97"
- path: /releases/name=ruby-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-xenial
    version: "97"
- path: /releases/name=cf-mysql/stemcell?
  type: replace
  value:
    os: ubuntu-xenial
    version: "97"
- path: /releases/name=silk/stemcell?
  type: replace
  value:
    os: ubuntu-xenial
    version: "97"
- path: /releases/name=staticfile-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-xenial
    version: "97"
- path: /releases/name=statsd-injector/stemcell?
  type: replace
  value:
    os: ubuntu-xenial
    version: "97"
- path: /releases/name=uaa/stemcell?
  type: replace
  value:
    os: ubuntu-xenial
    version: "97"
- path: /releases/name=bosh-dns-aliases/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/bosh-dns-aliases-0.0.2-ubuntu-xenial-97-20180719-221244-789694835.tgz
- path: /releases/name=bosh-dns-aliases/version
  type: replace
  value: 0.0.2
- path: /releases/name=bosh-dns-aliases/sha1
  type: replace
  value: 87543501088fd7364ae1549ed5d91b3cd73d80fc
- path: /releases/name=log-cache/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/log-cache-1.3.0-ubuntu-xenial-97-20180725-212500-046745603.tgz
- path: /releases/name=log-cache/version
  type: replace
  value: 1.3.0
- path: /releases/name=log-cache/sha1
  type: replace
  value: d14ee300c20de2fe91dffe664303a722f188adf8
